// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutTracker.Models;

#nullable disable

namespace WorkoutTracker.Migrations
{
    [DbContext(typeof(WorkoutDBContext))]
    [Migration("20260324152802_updatemig1")]
    partial class updatemig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkoutTracker.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightIncrement")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleGroup = "Back",
                            Name = "Pull Up",
                            Type = 2,
                            WeightIncrement = 0m
                        },
                        new
                        {
                            Id = 2,
                            MuscleGroup = "Back",
                            Name = "Lat Pulldown",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 3,
                            MuscleGroup = "Back",
                            Name = "Seated Cable Row",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 4,
                            MuscleGroup = "Back",
                            Name = "Barbell Bent-Over Row",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 5,
                            MuscleGroup = "Back",
                            Name = "T-Bar Row",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 6,
                            MuscleGroup = "Back",
                            Name = "Dumbbell Row",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 7,
                            MuscleGroup = "Biceps",
                            Name = "Barbell Bicep Curl",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 8,
                            MuscleGroup = "Biceps",
                            Name = "Preacher Curl",
                            Type = 1,
                            WeightIncrement = 2.5m
                        },
                        new
                        {
                            Id = 9,
                            MuscleGroup = "Biceps",
                            Name = "Cable Reverse Curl",
                            Type = 1,
                            WeightIncrement = 2.5m
                        },
                        new
                        {
                            Id = 10,
                            MuscleGroup = "Biceps",
                            Name = "Dumbbell Hammer Curl",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 11,
                            MuscleGroup = "Biceps",
                            Name = "Incline Dumbbell Curl",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 12,
                            MuscleGroup = "Legs",
                            Name = "Smith Machine Squat",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 13,
                            MuscleGroup = "Legs",
                            Name = "Seated Leg Curl",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 14,
                            MuscleGroup = "Legs",
                            Name = "Leg Extension",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 15,
                            MuscleGroup = "Legs",
                            Name = "Standing Calf Raise",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 16,
                            MuscleGroup = "Legs",
                            Name = "Leg Press",
                            Type = 1,
                            WeightIncrement = 10m
                        },
                        new
                        {
                            Id = 17,
                            MuscleGroup = "Shoulders",
                            Name = "Dumbbell Shoulder Press",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 18,
                            MuscleGroup = "Shoulders",
                            Name = "Rear Delt Fly",
                            Type = 1,
                            WeightIncrement = 2.5m
                        },
                        new
                        {
                            Id = 19,
                            MuscleGroup = "Shoulders",
                            Name = "Cable Face Pull",
                            Type = 1,
                            WeightIncrement = 2.5m
                        },
                        new
                        {
                            Id = 20,
                            MuscleGroup = "Shoulders",
                            Name = "Dumbbell Shrug",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 21,
                            MuscleGroup = "Chest",
                            Name = "Barbell Bench Press",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 22,
                            MuscleGroup = "Chest",
                            Name = "Smith Machine Incline Press",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 23,
                            MuscleGroup = "Chest",
                            Name = "Decline Chest Press Machine",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 24,
                            MuscleGroup = "Chest",
                            Name = "Pec Deck Fly",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 25,
                            MuscleGroup = "Chest",
                            Name = "Dumbbell Bench Press",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 26,
                            MuscleGroup = "Triceps",
                            Name = "Cable Overhead Tricep Extension",
                            Type = 1,
                            WeightIncrement = 2.5m
                        },
                        new
                        {
                            Id = 27,
                            MuscleGroup = "Triceps",
                            Name = "Cable Tricep Pushdown",
                            Type = 1,
                            WeightIncrement = 2.5m
                        },
                        new
                        {
                            Id = 28,
                            MuscleGroup = "Triceps",
                            Name = "Dumbbell Tricep Kickback",
                            Type = 1,
                            WeightIncrement = 2.5m
                        },
                        new
                        {
                            Id = 29,
                            MuscleGroup = "Core",
                            Name = "Machine Crunch",
                            Type = 1,
                            WeightIncrement = 5m
                        },
                        new
                        {
                            Id = 30,
                            MuscleGroup = "Core",
                            Name = "Hanging Leg Raise",
                            Type = 2,
                            WeightIncrement = 0m
                        });
                });

            modelBuilder.Entity("WorkoutTracker.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("OverallNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("WorkoutTracker.Models.WorkoutSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDropSet")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("SetOrder")
                        .HasColumnType("int");

                    b.Property<int?>("TargetReps")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("WorkoutTracker.Models.WorkoutSet", b =>
                {
                    b.HasOne("WorkoutTracker.Models.Exercise", "Exercise")
                        .WithMany("Sets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutTracker.Models.WorkoutSession", "Session")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("WorkoutTracker.Models.Exercise", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("WorkoutTracker.Models.WorkoutSession", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
